name: Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2

    - name: Add APT repositories
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

    - name: Install APT dependencies
      run: |
        sudo apt update
        sudo apt install --yes gcovr lcov cmake doctest-dev

    - name: Configure
      run: |
        cmake -S . -B Build/textum -DCMAKE_BUILD_TYPE=Debug -DTEXTUM_COVERAGE=ON

    - name: Prepare coverage report
      run: |
        COVERAGE_REPORT="$(cmake --build Build/textum --target coverage)"
        echo "$COVERAGE_REPORT"
        COVERAGE_VALUE="$(echo "$COVERAGE_REPORT" | grep TOTAL | awk '{print $4}')"
        echo $COVERAGE_VALUE
        echo "COVERAGE=$(echo $COVERAGE_VALUE)" >> $GITHUB_ENV

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{secrets.GIST}}
        gistID: abed75f53b2d54854a6cab8e52bb850c
        filename: textum_coverage.json
        label: Coverage
        message: ${{env.COVERAGE}}
        valColorRange: ${{env.COVERAGE}}
        maxColorRange: 100
        minColorRange: 0
