name: Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler:
          - name: "g++-12"
            package: "g++-12"
          - name: "g++-13"
            package: "g++-13"
          - name: "g++-14"
            package: "g++-14"
          - name: "clang++-15"
            package: "clang-15"
          - name: "clang++-17"
            package: "clang-17"
          - name: "clang++-19"
            package: "clang-19"
        build_type: ["Debug", "Release"]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Add APT repositories
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

    - name: Install APT dependencies
      run: |
        sudo apt update
        sudo apt install --yes ${{matrix.compiler.package}} cmake doctest-dev

    - name: Configure
      run: |
        cmake -S . -B Build/textum -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler.name}}

    - name: Build and test
      run: |
        cmake --build Build/textum --target check
